# Generated by Django 5.1.7 on 2025-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_enabled', models.BooleanField(default=False)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Percentage of ticket price charged as service fee', max_digits=5)),
                ('site_name', models.CharField(default='Nearby Happenings', max_length=100)),
                ('contact_email', models.EmailField(default='support@nearbyhappenings.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
